name: GitHub-Daily-Quotes

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-quotes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Random Quote
        uses: denvercoder1/quote-readme@v3
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUOTE_START_MARKER: '<!--✍️QUOTE-START-->'
          QUOTE_END_MARKER: '<!--✍️QUOTE-END-->'
          COMMIT_MESSAGE: "chore: update daily dev quote"
